### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [1]:
import numpy as np
a = np.array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
a.ndim
a.size
a.dtype
a.shape

(5,)

#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [2]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [3]:
a3 = np.array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])

#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [4]:
a3=a3.astype(float)
a3.dtype

dtype('float64')

#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [5]:
a4=np.array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
a4.flatten()[5:-1]

array([23, 45, 67,  8,  4,  6])

#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [6]:
a = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a[0]=10
a[-1]=0
a

array([10,  2,  3,  4,  5,  6,  7,  8,  9,  0])

#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [7]:
np.random.randint(10,99,(5,5))
# np.random.randint(10,99,25).reshape(5,5)

array([[14, 34, 60, 59, 13],
       [27, 10, 14, 53, 96],
       [12, 86, 24, 79, 97],
       [90, 73, 16, 34, 82],
       [91, 34, 51, 62, 63]])

#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [8]:
a=np.random.randint(1,100,7)
a, np.max(a), np.min(a)

(array([59, 14, 57, 44,  6, 81,  6]), 81, 6)

#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [9]:
a=np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
b=np.array([[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]])
c=np.array([[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]])
np.hstack([a,b,c]), np.vstack([a, b, c])

(array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
        [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
        [ 7,  8,  9, 17, 18, 19, 27, 28, 29]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]))

#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [10]:
arr = np.random.choice(100, 40, replace=False)
arr[arr>50] # 불린값 반환
#arr[np.where(n>50)] # 인덱스 반환

array([96, 81, 98, 94, 78, 99, 56, 74, 73, 77, 55, 57, 97, 52, 95, 87, 68])

#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [11]:
kor = np.array( [60,55,70,30,20,90])

In [12]:
kor.max()

90

In [13]:
kor[kor>=80]

array([90])

In [14]:
kor[(kor>=50)&(kor<=80)]

array([60, 55, 70])

In [22]:
round(np.mean(kor),3)
#np.average(kor, round(kor.mean(),3))

54.167

In [16]:
kor[kor<40]

array([30, 20])

In [17]:
np.sum(kor)

325

In [18]:
np.delete(kor, np.where(kor<40))
# num = kor[kor<40]
#np.delete(kor, num)

array([60, 55, 70, 90])

In [19]:
a_50 = np.where(kor>=50, kor*1.1, kor)
a_50

array([66. , 60.5, 77. , 30. , 20. , 99. ])

In [25]:
a = np.sort(kor)[::-1][:3]
a
#np.argsort(kor)[::-1][:3]

array([90, 70, 60])

In [21]:
for k in kor:
    if k >=70:
        print(k, "합격")
    else:
        print(k, "불합격")

60 불합격
55 불합격
70 합격
30 불합격
20 불합격
90 합격
